CREATE TABLE MATCHES(
    HOST VARCHAR(60),
    GUEST VARCHAR(60),
    GOLEHOST int,
    GOLEGUEST int
    );
    
INSERT INTO MATCHES VALUES('T_1','T_2',1,4);
INSERT INTO MATCHES VALUES('T_1','T_3',3,5);
INSERT INTO MATCHES VALUES('T_1','T_4',3,0);
INSERT INTO MATCHES VALUES('T_1','T_5',2,1);
INSERT INTO MATCHES VALUES('T_1','T_6',3,7);
INSERT INTO MATCHES VALUES('T_2','T_3',1,1);
INSERT INTO MATCHES VALUES('T_2','T_4',3,4);
INSERT INTO MATCHES VALUES('T_2','T_5',0,0);
INSERT INTO MATCHES VALUES('T_2','T_6',1,1);
INSERT INTO MATCHES VALUES('T_3','T_4',2,6);
INSERT INTO MATCHES VALUES('T_3','T_5',5,8);
INSERT INTO MATCHES VALUES('T_3','T_6',0,0);
INSERT INTO MATCHES VALUES('T_4','T_5',1,2);
INSERT INTO MATCHES VALUES('T_4','T_6',4,0);
INSERT INTO MATCHES VALUES('T_5','T_6',0,1);